version: '3'
services:
  back_kts:
    build: ./Backend
    ports:
      - "8080:80"
  front_kts:
    build: ./Frontend
    ports:
      - "9000:80"
  redis:
    image: redis
    ports:
      - "6379:6379"